### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#85] opened 2015-04-10 00:13 UTC
I run the following command

XXXXXXXXXXXXXXXX:~$ npm install --global superscript

Then I see the following errors

> kerberos@0.0.7 install /XXXXXXXXXXXXXX/XXXXXXXXXXXx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos

> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.21 install /xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

> leveldown@0.10.4 install /xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/sfacts/node_modules/leveldown
> node-gyp rebuild

make: Entering directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/sfacts/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o
make: g++: Command not found
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o] Error 127
make: Leaving directory `/xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/sfacts/node_modules/leveldown/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/sfacts/node_modules/leveldown
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> WNdb@3.1.1 postinstall /xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/WNdb
> node unpack.js WNdb-3.1.tar.gz

Extracting WNdb-3.1.tar.gz

> wndb-with-exceptions@3.0.1 postinstall /xxxxxx/xxxxx/.node/lib/node_modules/superscript/node_modules/lemmer/node_modules/wndb-with-exceptions
> node unpack.js WNdb-3.0.tar.gz

npm ERR! leveldown@0.10.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.4 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--global" "superscript"
npm ERR! cwd /xxxxxx/xxxxx
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by silentrob** [comment] 2015-04-10 05:44
If you have switched from node 10 to 12 and back you may need to run `npm rebuild` That will re-compile the binary modules and should get you unblocked,

**Comment by airport-transfers** [comment] 2015-04-10 20:35
Thanks, but it happen the same as before, I receive the same error. I will try to do the same test on a different nodejs and mongodb server too and let you know.

**Comment by silentrob** [comment] 2015-04-11 00:00
Okay, let me know how it goes. Ive tested it on Mac in both 10 and 12. The only problem I had was the binary modules.. and either removed the node_modules folder and running npm install again fixed it.

`npm rebuild` should do the same thing.

**Comment by silentrob** [comment] 2015-08-14 06:55
Im closing this issue now since I can not reproduce it locally.

**Closed by silentrob** 2015-08-14 06:55 UTC
