### ISSUE TITLE
Variable length with more than x.

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#99] opened 2015-04-27 15:58 UTC
From the examples : 
```
+ *~1 hello
```

This allows you to have variable length of words before hello. The length can vary from 0 to 1. This doesnt cater for changing the minimum number of words to expect ( only the maximum ). How do you say I want 5-10 words for example ? 

I tried something like `*5 *~5` - Is this correct ? When I tried it - it did not seem to work as far as I could tell.

On a side note : 
Consider integrating gitter ( www.gitter.im ) ? Most of these questions that I am asking could just be that - questions - and could easily be answered in gitter perhaps ? 
https://github.com/angular-dragdrop/angular-dragdrop ( see here for gitter badge in the readme )

**Comment by silentrob** [comment] 2015-04-27 18:21
Wow, interesting. Im going to add a test for the min max case, I feel that should work.

I will also look at setting up a channel (gitter, slack or irc?)

**Comment by ganarajpr** [comment] 2015-04-27 18:25
gitter or slack..

**Comment by silentrob** [comment] 2015-04-27 19:07
Gitter is in for now. That might change down the road to slack. (it is more bot friendly and could be a fun bot playground.)

**Comment by ganarajpr** [comment] 2015-04-27 19:12
Yeah.. I agree.. Slack will be fun too.

On Mon, Apr 27, 2015 at 8:07 PM, Rob Ellis <notifications@github.com> wrote:

> Gitter is in for now. That might change down the road to slack. (it is
> more bot friendly and could be a fun bot playground.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silentrob/superscript/issues/99#issuecomment-96782613>
> .
>



-- 
Regards,
Ganaraj P R

**Comment by silentrob** [comment] 2015-04-27 20:40
Okay, I found the problem, but don't have a solution yet - just pushed a failing test.
The problem is we insert a literal " " space between tokens. So in order to make this work, we either need to collapse that space out if we use back to back tokens OR come up with a new API for mix/max wildcards. 

What are your thoughts.

**Comment by ganarajpr** [comment] 2015-04-27 21:12
Extension to the current api seems to be much more intuitive than the two part version.

So, here are a few suggestions I have in mind for this : 

```
*(1-3)
*(5)
```

It is your call whether you want the brackets or not. Or even perhaps square brackets ? [].

On a side note : Have you considered using something like jison for the parser ? The reason I am asking you this is that it would be much easier in the early days of defining something like this to use a Parser Expression Generator than write your own parser. Perhaps in terms of performance a standalone parser is faster. But , in early days you might want a faster iteration than parsing speed ? Something to think about perhaps ?

**Comment by silentrob** [comment] 2015-04-28 00:50
I think jison is a great idea. Im not sure how much effort it would take, but it seems like it could add a lot of power and flexibility to the scripting interface.

I will take a closer look.

**Comment by silentrob** [comment] 2015-04-28 02:48
Okay, this has now landed. I will keep this open until I update the docs in 0.8.5

**Comment by silentrob** [comment] 2015-08-14 06:53
This is done... and we have slack now and updated docs YAY

**Closed by silentrob** 2015-08-14 06:53 UTC
Labels: enhancement
