### ISSUE TITLE
first time install parse error

### ISSUE THREAD

**Issue by brw31415** [silentrob/superscript#229] opened 2016-01-14 14:44 UTC
parse error:

node 0.12
debian jessie
no install errors

parse                                                                  
parse topics                                                                                                        
module.js:355                                                                                                       
  Module._extensions[extension](this, filename);                                                                    
                               ^                                                                                    
Error: Module version mismatch. Expected 14, got 47.                                                                
    at Error (native)                                                                                               
    at Module.load (module.js:355:32)                                                                               
    at Function.Module._load (module.js:310:12)                                                                     
    at Module.require (module.js:365:17)                                                                            
    at require (module.js:384:17)                                                                                   
    at Object.<anonymous> (/home/brw314/.node_local/lib/node_modules/superscript/node_modules/re2/re2.js:3:11)      
    at Module._compile (module.js:460:26)                                                                           
    at Object.Module._extensions..js (module.js:478:10)                                                             
    at Module.load (module.js:355:32)                                                                               
    at Function.Module._load (module.js:310:12) 

cat topics/main.ss                                                     
+ ~emohello [*~2]                                                                                                   
- Hi from your bot.                           

                
everything installed, no errors, but these warnings:

npm install                                                            
npm WARN deprecated WNdb@3.1.2: WNdb has been superceded by wordnet-db.  Please update your dependency.
npm WARN deprecated WNdb@3.1.1: WNdb has been superceded by wordnet-db.  Please update your dependency.
npm WARN engine stream-worker@0.0.1: wanted: {"node":"~0.10.0"} (current: {"node":"0.12.9","npm":"2.14.9"})
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by Lewwwk** [comment] 2016-01-14 16:04
Can you describe the steps to reproduce the error? Also might be helpful to see the warnings that you are pasting in your issues formatted as code. For more on how to do that, you can take a look here: https://guides.github.com/features/mastering-markdown/

One thing I'm wondering is if you maybe have a formatting error your .ss files.

**Comment by brw31415** [comment] 2016-01-14 20:59
I'm sorry, I dont see the "code" markdown option in this window.  I've removed and completely re-installed a couple of times, this is  what I did:

Clone from github it to my machine, then "run install" innthat root (superscript) directory, which seems to work to work with some warnings,the complete output is here: http://pastebin.com/uJfEuXxB 

Then run " bot-init mybot --client telnet "  , then cd mybot  and run "npm install" again complete output of this second install 

here: http://pastebin.com/YH9QSWDS , 
then in that directory .../mybot   run "parse", where the errors occur.  one thing peculiar is that the same error occurs , even before i run the second install.


I don't think it's the .ss files because the same error occurred before  touched them.

**Comment by Lewwwk** [comment] 2016-01-14 22:22
I'm sorry, I'm having a hard time following this. I'd be able to be more helpful if you were running on the same environment I am, but alas, I can't test a Debian install.

**Comment by brw31415** [comment] 2016-01-14 22:59
I also am trying an ubuntu install (14.01) , node 0.12) having a different
problem with that...

after first install, ie cloning and running "npm install" (not global), the
 bot-init  command not found. if i try npm install -g there are other
problems, but not included here

the output here: http://pastebin.com/8BXGAjxC


if you don't mind , i can send you log in credentials encrypted for the
debian system








On Thu, Jan 14, 2016 at 5:22 PM, Michael Lewkowitz <notifications@github.com

**Comment by Lewwwk** [comment] 2016-01-15 01:25
I just created a superscript bot called `testbot` with a telnet client following these steps on an OSX machine running node 0.12.7 npm 2.11.3:

1. Clone superscript
2. Open a terminal window at the superscript directory and enter the following at the prompts:
  * `npm install`
  * `cd ..`
  * `./superscript/bin/bot-init.js testbot --client telnet`
  * `cd testbot`
  * `npm install`
  * `parse`
  * `npm start`

3. Open a new terminal window and enter the following at the prompts: 
  * `telnet localhost 2000` (change port as required)
  * `hello` <- you are now talking with your bot

**Comment by brw31415** [comment] 2016-01-15 02:45
appears to hang on wordnet extract, as dicussed here->
https://github.com/moos/wordnet-db/issues/7

my output here:
http://pastebin.com/GJChzBkQ

On Thu, Jan 14, 2016 at 8:25 PM, Michael Lewkowitz <notifications@github.com

**Comment by Lewwwk** [comment] 2016-01-15 11:20
I'm also running mongodb 2.0.52 and mongoose 3.8.24. Looks like wordnet is disagreeing with something in your environment. You may want to look into any dependencies it has. 






On Thu, Jan 14, 2016 at 6:45 PM -0800, "brw31415" <notifications@github.com> wrote:










appears to hang on wordnet extract, as dicussed here->

https://github.com/moos/wordnet-db/issues/7



my output here:

http://pastebin.com/GJChzBkQ



On Thu, Jan 14, 2016 at 8:25 PM, Michael Lewkowitz <notifications@github.com

**Comment by brw31415** [comment] 2016-01-16 22:42
after i did "npm cache clean"
the second part install in testbot dir ran:
http://pastebin.com/egVLc93J

parse ran fine and generated the data.json file.

however, when i ran "npm run" (inside testbot dir)

i get this:

http://pastebin.com/SeUzwa4S




On Fri, Jan 15, 2016 at 6:20 AM, Michael Lewkowitz <notifications@github.com
> wrote:

> I'm also running mongodb 2.0.52 and mongoose 3.8.24. Looks like wordnet is
> disagreeing with something in your environment. You may want to look into
> any dependencies it has.
>
>
>
>
>
>
> On Thu, Jan 14, 2016 at 6:45 PM -0800, "brw31415" <

**Comment by brw31415** [comment] 2016-01-16 22:44
whoops! i needed to run npm cahe clean again, now seems to work

**Comment by brw31415** [comment] 2016-01-16 22:51
however, when i try to run it, it comes back with this:

npm run
Lifecycle scripts included in testbot:
  start
    node server.js


nothing in package.json except:

{
  "name": "testbot",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "superscript": "latest",
    "sfacts": "latest",
    "mongoose": "3.8.24",
    "debug": "~2.0.0"
  }
}

**Comment by Lewwwk** [comment] 2016-01-16 23:00
Have you tried `npm start`?

**Comment by brw31415** [comment] 2016-01-16 23:13
then i went back to the debian system, and used npm cache clean profusely,

everything ran fine, except hwhen i got to npm run:

 npm start

> testbot@0.0.0 start /home/brw314/javascript/testbot
> node server.js
{ [Error: Cannot find module '../build/Release/bson'] code:
'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [MongoError: not authorized for query on superscriptDB.topics] name:
'MongoError' }
/home/brw314/javascript/testbot/node_modules/superscript/lib/topics/import.js:123

topic.createGambit(gambitData, function (err3, gambit) {

**Comment by brw31415** [comment] 2016-01-16 23:18
but when i used "npm update"  (sry i'm not familar with node stuff)
npm run came back with same result as on ubuntu:

npm run
Lifecycle scripts included in testbot:
  start
    node server.js

so i guess atleast i have the two systems a bit closer and behaving the same

**Comment by Lewwwk** [comment] 2016-01-16 23:51
Have you tried 'npm start' on your ubuntu box? That is the command from the steps I shared above.

'npm run' is doing exactly what it is supposed to. You can learn more here: https://docs.npmjs.com/cli/run-script.

**Comment by brw31415** [comment] 2016-01-17 03:50
when i ran on the ubuntu box:
npm cache clean
npm update
npm start
http://pastebin.com/nZ2cESwK

On Sat, Jan 16, 2016 at 6:51 PM, Michael Lewkowitz <notifications@github.com

**Comment by Lewwwk** [comment] 2016-01-17 15:58
I'm not sure why you are doing 'npm clean cache' but that could be why you
are missing lower level dependencies. npm update only updates top level
unless specified. Otherwise perhaps there is something else with your
environment. Perhaps you can try the recommended steps from the beginning
again for a new bot. At this point that's all I can suggest. Best of luck.

**Comment by brw31415** [comment] 2016-01-18 03:49
after a  couple more tries, and clearing the environments, it works!
thank you very much for your assistance and patience

**Comment by Lewwwk** [comment] 2016-01-18 13:34
Did you get it working on both unbuntu and debian?

Now that your issue is resolved, you can also close it.

**Closed** 2016-01-18 18:18 UTC
