### ISSUE TITLE
Slack Integration Topic Issue.

### ISSUE THREAD

**Issue by kgao** [silentrob/superscript#116] opened 2015-06-23 17:08 UTC
I have followed the docs, built my local bot and integrated to slack.
However, after sever times tried:

1. When I update the topic, it didn't rly reply correctly.
2. Try delete data.json, re-parse the .ss topic, it still remains the old responses, like the first time it loads in slack.

Since data.json looks fine to me, I am not sure if this is a known cache issue related to slack. But there seems not much we can do in slack beside setting up the key.

I hope this got resolved asap.

Thank you!

**Comment by ganarajpr** [comment] 2015-06-23 17:20
duplicate of #95 . 

I have provided an interim fix for this issue in there.

**Closed** 2015-08-14 06:48 UTC
